### ISSUE TITLE
Remove weekly email

### ISSUE THREAD

**Issue by bkDJ** [crowdbreaks/crowdbreaks#107]
Suggested on [slack](https://digitalepidemiology.slack.com/archives/C37BXFDK2/p1696837257921879).

**Comment by yannis** [comment]
Fixed by removing the task from Heroku Scheduler:
<img width="1522" alt="CleanShot 2023-10-13 at 14 20 58@2x" src="https://github.com/digitalepidemiologylab/crowdbreaks/assets/30563/797ebd73-38f7-46e3-acd0-6e757e1660ba">

CC @bkDJ @lauespinosa
